---
- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Ensure Nginx is running and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
