---
- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Add Jenkins repository key
  apt_key:
    url: http://pkg.jenkins.io/debian/jenkins.io.key  # Change https to http
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian binary/"
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start Jenkins service
  systemd:
    name: jenkins
    enabled: yes
    state: started
