---
# Penetration testing environment variables
env_name: pentest
app_version: "1.0.0-pentest"

# Security scanning settings
security_scan: true
vulnerability_scan: true

# Web server configuration
web_port: 80
web_root: /var/www/html

# Application settings
debug_mode: false
log_level: info
