---
- name: Install PHP and extensions
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-fpm
    - php-mysql
    - php-curl
    - php-json
    - php-mbstring

- name: Start and enable PHP-FPM
  systemd:
    name: php8.1-fpm
    state: started
    enabled: yes
